const { NODE_ENV, PORT, FRONTEND_URL, CAT_API_URL, CAT_API_KEY, DATABASE_URI, JWT_SECRET, JWT_EXPIRES_IN } = process.env

export {
    NODE_ENV,
    PORT,
    FRONTEND_URL,
    CAT_API_URL,
    CAT_API_KEY,
    DATABASE_URI,
    JWT_SECRET,
    JWT_EXPIRES_IN
}